name: Deploy Quatricmorph to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm" # or 'yarn'/'pnpm' depending on your package manager

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: npm ci # or yarn install --frozen-lockfile

      - name: Build Nextra site
        run: npm run build
        env:
          NODE_ENV: production

      - name: Generate search index
        run: npm run postbuild

      - name: Verify build output
        run: |
          if [ ! -d "./out" ]; then
            echo "Error: ./out directory not found after build"
            echo "Available directories:"
            ls -la
            exit 1
          fi
          echo "✅ Build successful - ./out directory found"
          echo "Build contents:"
          ls -la ./out
          echo "Checking for Pagefind:"
          if [ -d "./out/_pagefind" ]; then
            echo "✅ Pagefind search index found"
            ls -la ./out/_pagefind
          else
            echo "⚠️ Pagefind search index not found"
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
